(defun color-theme-python ()
  (interactive)
  (color-theme-install
   '(color-theme-python
      ((background-color . "#ffffff")
      (background-mode . light)
      (border-color . "#ffffff")
      (cursor-color . "#000000")
      (foreground-color . "#000000")
      (mouse-color . "black"))
     (fringe ((t (:background "#ffffff"))))
     (mode-line ((t (:foreground "#000000" :background "#e5e5e5"))))
     (region ((t (:background "#f4f5f6"))))
     (font-lock-builtin-face ((t (:foreground "#c36fa8"))))
     (font-lock-comment-face ((t (:foreground "#6d786d"))))
     (font-lock-function-name-face ((t (:foreground "#102cc1"))))
     (font-lock-keyword-face ((t (:foreground "#c18a15"))))
     (font-lock-string-face ((t (:foreground "#c73b29"))))
     (font-lock-type-face ((t (:foreground"#199915"))))
     (font-lock-variable-name-face ((t (:foreground "#000000"))))
     (minibuffer-prompt ((t (:foreground "#7299ff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'color-theme-python)
